spring:
  application:
    name: turbine
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
turbine:
  aggregator:
    cluster-config: default
#  配置Eureka中的serviceId列表，表明监控哪些服务
  app-config: product-view-service-feign
  cluster-name-expression: new String("default")
