# 因为会启动多个 product-data-service, 所以端口号由用户自动设置，推荐 8001,8002,8003
#server:
#  port: 8001
spring:
  application:
    name: product-data-service
#  profiles:
#    active: @spring.profiles.active@
  zipkin:
    base-url: http://localhost:9411
  redis:
    host: localhost
    port: 6379
    # Redis数据库索引（默认为0）
    database: 0
    timeout: 6000 # key超时时间，2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
    # 连接池配置，2.0中直接使用jedis或者lettuce配置连接池
    jedis:
      pool:
        # 最大空闲连接数
        max-idle: 8
        # 最小空闲连接数
        min-idle: 4
        # 等待可用连接的最大时间，负数为不限制
        max-wait: -1
        # 最大活跃连接数，负数为不限制
        max-active: 8
        time-between-eviction-runs: -1
eureka:
#  instance:
#    hostname: localhost
  client:
    service-url:
      # 设置注册中心的地址： http://localhost:8761/eureka/
      # ，与 eureka-server 中的配置 application.yml 遥相呼应
      defaultZone: http://localhost:8761/eureka

